runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /js
  static_dir: js
  
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /style
  static_dir: style
  
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
