target 'GoCar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoCar
	
    pod 'Charts', '~>3.4.0'

    pod 'Firebase/Firestore'

    pod 'Firebase/Auth'

  target 'GoCarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoCarUITests' do
    # Pods for testing
  end

end
